import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';
import path from 'node:path';

// Migrated from Create React App to Vite. JSX lives in `.jsx` files; plain
// logic/config stays in `.js`. The Rust→WASM core (core/pkg) and shadcn/ui
// components are TypeScript — Vite transpiles both side by side.
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      injectRegister: 'auto',
      includeAssets: ['favicon.ico', 'logo192.png', 'logo512.png'],
      manifest: {
        short_name: 'Desk Dazzle',
        name: 'Desk Dazzle',
        start_url: '/apps',
        display: 'standalone',
        theme_color: '#000000',
        background_color: '#ffffff',
        icons: [
          { src: 'favicon.ico', sizes: '64x64 32x32 24x24 16x16', type: 'image/x-icon' },
          { src: 'logo192.png', type: 'image/png', sizes: '192x192' },
          { src: 'logo512.png', type: 'image/png', sizes: '512x512' },
        ],
        shortcuts: [
          { name: 'Documentation', url: '/docs' },
        ],
      },
      workbox: {
        // Precache the shell *including the wasm core* so every tool keeps
        // working with no network after the first visit.
        globPatterns: ['**/*.{js,css,html,ico,png,svg,ttf,wasm,woff2}'],
        maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,
        cleanupOutdatedCaches: true,
        navigateFallback: '/index.html',
      },
    }),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      // Rust/WASM output generated by wasm-pack into core/pkg (prebuilt +
      // committed, so plain `npm run build` needs no Rust toolchain).
      '@core': path.resolve(__dirname, './core/pkg'),
    },
  },
  build: {
    outDir: 'dist',
  },
  server: {
    port: 3000,
    open: true,
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './src/setupTests.js',
  },
});
