import React, { useContext, useRef, useState } from 'react';
import { toast } from 'sonner';
import { Sparkles, Download, Upload, RotateCcw } from 'lucide-react';
import { ThemeContext } from '../../../App';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { TOKEN_GROUPS, DEFAULT_LIGHT } from '@/lib/settings/tokens';
import {
  resolveColor, generateDarkFromLight, exportSettings, parseSettingsFile,
} from '@/lib/settings/theme';
import ColorRow from './ColorRow';
import ThemePreview from './ThemePreview';

export default function ColorsPanel({ settings, setColor, setPalette, update, replaceAll }) {
  const { theme } = useContext(ThemeContext);
  // Start on whichever palette matches the theme currently on screen.
  const [mode, setMode] = useState(theme ? 'dark' : 'light');
  const fileRef = useRef(null);

  const resolve = (token) => resolveColor(settings, mode, token);

  const autoGenerateDark = () => {
    const light = {};
    for (const token of Object.keys(DEFAULT_LIGHT)) light[token] = resolveColor(settings, 'light', token);
    setPalette('dark', generateDarkFromLight(light));
    setMode('dark');
    toast.success('Dark theme generated from your light theme');
  };

  const doExport = () => {
    const blob = new Blob([exportSettings(settings)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'deskdazzle-theme.json';
    a.click();
    URL.revokeObjectURL(url);
  };

  const doImport = async (file) => {
    try {
      const next = parseSettingsFile(await file.text());
      replaceAll(next);
      toast.success('Theme imported');
    } catch {
      toast.error('Could not read that theme file');
    }
  };

  const resetColors = () => {
    update({ colors: { light: {}, dark: {} } });
    toast.success('Colours reset to defaults');
  };

  return (
    <div className="flex flex-col gap-4">
      {/* Which palette to edit */}
      <div className="grid grid-cols-2 gap-2">
        {['light', 'dark'].map((m) => (
          <button
            key={m}
            type="button"
            onClick={() => setMode(m)}
            aria-pressed={mode === m}
            className={cn(
              'rounded-lg border py-2 text-sm font-medium capitalize transition-colors',
              mode === m ? 'border-ring bg-accent text-accent-foreground ring-2 ring-ring' : 'border-border hover:bg-accent/50',
            )}
          >
            {m} theme
          </button>
        ))}
      </div>

      <ThemePreview resolve={resolve} />

      <div className="flex flex-wrap gap-2">
        {mode === 'dark' && (
          <Button size="sm" variant="secondary" onClick={autoGenerateDark}>
            <Sparkles className="size-4" /> Auto from light
          </Button>
        )}
        <Button size="sm" variant="outline" onClick={doExport}>
          <Download className="size-4" /> Export
        </Button>
        <Button size="sm" variant="outline" onClick={() => fileRef.current?.click()}>
          <Upload className="size-4" /> Import
        </Button>
        <Button size="sm" variant="ghost" onClick={resetColors}>
          <RotateCcw className="size-4" /> Reset
        </Button>
        <input
          ref={fileRef}
          type="file"
          accept="application/json,.json"
          className="hidden"
          onChange={(e) => {
            const f = e.target.files?.[0];
            if (f) doImport(f);
            e.target.value = '';
          }}
        />
      </div>

      <Separator />

      <div className="flex flex-col gap-4">
        {TOKEN_GROUPS.map((group) => (
          <section key={group.id}>
            <h4 className="mb-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              {group.label}
            </h4>
            <div className="divide-y divide-border/60">
              {group.tokens.map((token) => (
                <ColorRow
                  key={token.id}
                  token={token}
                  value={resolve(token.id)}
                  onChange={(val) => setColor(mode, token.id, val)}
                />
              ))}
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}
